#ifndef COMM_ERROR_CODE_H_432874328987687643287432876
#define COMM_ERROR_CODE_H_432874328987687643287432876

#include "common/vbh_comm_def_export.h"
namespace VBH
{
	enum __ERROR_CORE
	{
		EN_OK_TYPE = 0,
		EN_NOT_READY_ERROR_TYPE = -1, //未准备就绪
		EN_REENTRY_ERROR_TYPE = -2, //重入错误，重复提交错误
		EN_TIMEOUT_ERROR_TYPE = -3, //超时错误
		EN_NETWORK_ERROR_TYPE = -4,
		EN_SYSTEM_ERROR_TYPE = -5,
		EN_ENCRYPT_ERROR_TYPE = -6,
		EN_DECRYPT_ERROR_TYPE = -7,
		EN_DECODE_ERROR_TYPE = -8,
		EN_SIGNATURE_VERIFY_ERROR_TYPE = -9,
		EN_NONCE_VERIFY_ERROR_TYPE = -10, //随机数校验失败错误
		EN_REPEAT_INFO_ERROR_TYPE = -11, //重复信息错误，用户重复注册、信息重复等错误
		EN_CANNOT_FOUND_CHANNEL_ERROR_TYPE = -12, //未找到channel
		EN_CANNOT_FOUND_USER_ERROR_TYPE = -13, //未找到用户
		EN_ORDER_CPS_BLOCK_CACHE_ALREADY_FULL = -14,  // order-cps的 block cache已满
		EN_UPDATE_INFO_CONFLICT_ERROR_TYPE = -15, //流水号不一致，发生冲突 错误
		EN_CANNOT_FOUND_TRANSACTION_ERROR_TYPE = -16,
		EN_CANNOT_FIND_SESSION_ERROR_TYPE = -17,
		EN_CLIENT_CANCEL_REGIST_ERROR_TYPE = -18,
		EN_CC_REPORT_ERROR_TYPE = -19,
		EN_REGIST_USER_IS_REFUSED = -20,
		EN_DISTRIBUTE_REPEATED_BLOCK_ID = -21, //TODO，去掉这个错误码，待复用
		EN_CANNOT_FOUND_INFORMATION_ERROR_TYPE = -22, //未找到information
		EN_CANNOT_FOUND_CHANNEL_INFORMATION_GROUP_ERROR_TYPE = -23, //未找到 信息组 cig //TODO，去掉这个错误码，待复用
	};

	VBH_COMM_DEF_EXPORT const char* GetErrorString(int nErrorCode);
}

#endif
