#ifndef COMM_ID_DEF_H_342789423809732182139785892349782317556823482318875486723456
#define COMM_ID_DEF_H_342789423809732182139785892349782317556823482318875486723456

#include "dsc/dsc_comm_def.h"

namespace VBH
{
	enum
	{
		/* order */
		EN_ORDER_MANAGER_APP_TYPE = 1, 
		EN_ORDER_SERVICE_APP_TYPE = 2,

		/* endorser */
		EN_ENDORSER_APP_TYPE = 11,

		/* anchor */
		EN_ANCHOR_MANAGER_APP_TYPE = 21,
		EN_ANCHOR_SERVICE_APP_TYPE,

		/* x committer */
		EN_X_COMMITTER_APP_TYPE = 30,

		/* cc */
		EN_CC_APP_TYPE = 10000,

		EN_VBH_KERNEL_APP_TYPE = 999,
		EN_CA_SERVER_APP_TYPE = 888,

		EN_VBH_USER_INFO_SDK_APP_TYPE = 666
	};

	enum
	{
		/* order */
		EN_ORDER_CHANNEL_PROCESS_SERVICE_TYPE = DSC::EN_MIN_USER_TASK_TYPE + 1,
		EN_ORDER_CHANNEL_MANAGER_SERVICE_TYPE,

		/* endorser */
		EN_CRYPT_ENDORSER_SERVICE_CONTAINER_TYPE,
		EN_ENDORSER_SERVICE_CONTAINER_TYPE,
		EN_CRYPT_ENDORSER_SERVICE_TYPE,
		EN_ENDORSER_SERVICE_TYPE,
		EN_CRYPT_TRANSFER_AGENT_SERVICE_TYPE,
		EN_TRANSFER_AGENT_SERVICE_TYPE,

		/* anchor */
		EN_ANCHOR_SERVICE_CONTAINER_TYPE,
		EN_ANCHOR_SERVICE_TYPE,
		EN_ANCHOR_PEER_MANAGER_CLIENT_SERVICE,
		EN_ANCHOR_PEER_MANAGER_SERVER_SERVICE,

		/* x committer = transaction committer + user-committer + information-committer */
		EN_X_COMMITTER_SERVICE_CONTAINER_TYPE,
		EN_X_COMMITTER_SERVICE_TYPE,

		/* client sdk */
		EN_VBH_CRYPT_CLIENT_SERVICE_TYPE,
		EN_VBH_CLIENT_SERVICE_TYPE,

		EN_MIN_VBH_SERVICE_TYPE,
	};

	enum
	{
		/* 初始化流程涉及消息 */
		EN_QUERY_PTS_ADDR_TAS_CMS_REQ = DSC::EN_MIN_USER_MSG + 1,
		EN_QUERY_PTS_ADDR_CMS_TAS_RSP,
		EN_QUERY_CBS_ADDR_AS_CMS_REQ,
		EN_QUERY_CBS_ADDR_CMS_AS_RSP,
		EN_REGISTER_AS_CPS_REQ,

		/* 注册用户流程涉及消息 */
		EN_REGIST_USER_API_CLT_REQ,
		EN_REGIST_USER_CLT_CLT_REQ,
		EN_REGIST_USER_CLT_CLT_RSP,
		EN_REGIST_USER_CLT_CLT_NOTIFY,
		EN_CRYPT_REGIST_USER_CLT_ES_REQ,
		EN_CRYPT_REGIST_USER_ES_CLT_RSP,
		EN_REGIST_USER_CLT_ES_REQ, 
		EN_REGIST_USER_ES_CLT_RSP,
		EN_REGIST_USER_ES_CC_REQ,
		EN_REGIST_USER_CC_ES_RSP,
		EN_CRYPT_SUBMIT_REGIST_TRANSACTION_CLT_ES_REQ,
		EN_CRYPT_SUBMIT_REGIST_TRANSACTION_ES_CLT_RSP,
		EN_SUBMIT_REGIST_TRANSACTION_CLT_ES_REQ,
		EN_SUBMIT_REGIST_TRANSACTION_ES_CLT_RSP,
		EN_SUBSCRIBE_TRANSACTION_RESULT_ES_XCS_REGUSR_REQ,
		EN_SUBSCRIBE_TRANSACTION_RESULT_XCS_ES_REGUSR_RSP,
		EN_CRYPT_CANCEL_REGIST_TRANSACTION_CLT_ES_REQ,
		EN_CANCEL_REGIST_TRANSACTION_CLT_ES_REQ,
		EN_CRYPT_SUBSCRIBE_REGIST_TRANSACTION_ES_CLT_NOTIFY,
		EN_SUBSCRIBE_REGIST_TRANSACTION_ES_CLT_NOTIFY,
		EN_SUBMIT_REGIST_TRANSACTION_ES_TAS_REQ,
		EN_SUBMIT_REGIST_TRANSACTION_TAS_ES_RSP,
		EN_SUBMIT_REGIST_TRANSACTION_TAS_CPS_REQ,
		EN_SUBMIT_REGIST_TRANSACTION_CPS_TAS_RSP,

		/* 注销用户流程涉及消息 */
		EN_CRYPT_UNREGIST_USER_REQ_MSG,
		EN_CRYPT_UNREGIST_USER_RSP_MSG,
		EN_UNREGIST_USER_REQ_MSG,
		EN_UNREGIST_USER_RSP_MSG,	

		/* 查询用户流程涉及消息 */
		EN_QUERY_USER_INFO_API_CLT_REQ,
		EN_QUERY_USER_INFO_CLT_CLT_REQ,
		EN_QUERY_USER_INFO_CLT_CLT_RSP,
		EN_CRYPT_QUERY_USER_INFO_CLT_ES_REQ,
		EN_CRYPT_QUERY_USER_INFO_ES_CLT_RSP,
		EN_QUERY_USER_INFO_CLT_ES_REQ,
		EN_QUERY_USER_INFO_ES_CLT_RSP,
		EN_QUERY_USER_FULL_INFO_ES_XCS_REQ,
		EN_QUERY_USER_FULL_INFO_XCS_ES_RSP,
		EN_QUERY_USER_INFO_ES_XCS_REQ,
		EN_QUERY_USER_INFO_XCS_ES_RSP,

		/* 发起Transaction流程涉及消息 */
		EN_PROPOSE_API_CLT_REQ,
		EN_PROPOSE_CLT_CLT_REQ,
		EN_PROPOSE_CLT_CLT_RSP,
		EN_PROPOSE_CLT_CLT_NOTIFY,
		EN_CRYPT_SUBMIT_PROPOSAL_CLT_ES_REQ,
		EN_CRYPT_SUBMIT_PROPOSAL_ES_CLT_RSP,
		EN_SUBMIT_PROPOSAL_CLT_ES_REQ,
		EN_SUBMIT_PROPOSAL_ES_CLT_RSP,
		EN_QUERY_CRYPT_KEY_PROPOSE_ES_XCS_REQ,
		EN_QUERY_CRYPT_KEY_PROPOSE_XCS_ES_RSP,
		EN_SUBMIT_PROPOSAL_ES_CC_REQ,
		EN_SUBMIT_PROPOSAL_CC_ES_RSP,
		EN_QUERY_USER_INFO_CC_XCS_REQ,
		EN_QUERY_USER_INFO_XCS_CC_RSP,
		EN_QUERY_INFORMATION_CC_XCS_REQ,
		EN_QUERY_INFORMATION_XCS_CC_RSP,
		EN_CRYPT_SUBMIT_PROPOSAL_TRANSACTION_CLT_ES_REQ,
		EN_CRYPT_SUBMIT_PROPOSAL_TRANSACTION_ES_CLT_RSP,
		EN_SUBMIT_PROPOSAL_TRANSACTION_CLT_ES_REQ,
		EN_SUBMIT_PROPOSAL_TRANSACTION_ES_CLT_RSP,
		EN_SUBSCRIBE_TRANSACTION_RESULT_ES_XCS_PROPOSE_REQ,
		EN_SUBSCRIBE_TRANSACTION_RESULT_XCS_ES_PROPOSE_RSP,
		EN_CRYPT_CANCEL_PROPOSAL_TRANSACTION_CLT_ES_REQ,
		EN_CANCEL_PROPOSAL_TRANSACTION_CLT_ES_REQ,
		EN_CRYPT_SUBSCRIBE_PROPOSE_TRANSACTION_ES_CLT_NOTIFY,
		EN_SUBSCRIBE_PROPOSE_TRANSACTION_ES_CLT_NOTIFY,
		EN_SUBMIT_PROPOSAL_TRANSACTION_ES_TAS_REQ,
		EN_SUBMIT_PROPOSAL_TRANSACTION_TAS_ES_RSP,
		EN_SUBMIT_PROPOSAL_TRANSACTION_TAS_CPS_REQ,
		EN_SUBMIT_PROPOSAL_TRANSACTION_CPS_TAS_RSP,
		EN_DISTRIBUTE_BLOCK_CPS_AS_REQ,
		EN_DISTRIBUTE_BLOCK_AS_CPS_RSP,
		EN_DISTRIBUTE_BLOCK_AS_XCS_REQ,
		EN_DISTRIBUTE_BLOCK_XCS_AS_RSP,

		/* 查询Transaction流程涉及消息 */
		EN_QUERY_TRANS_INFO_API_CLT_REQ,
		EN_QUERY_TRANS_INFO_CLT_CLT_REQ,
		EN_QUERY_TRANS_INFO_CLT_CLT_RSP,
		EN_CRYPT_QUERY_TRANS_INFO_CLT_ES_REQ,
		EN_CRYPT_QUERY_TRANS_INFO_ES_CLT_RSP,
		EN_QUERY_TRANS_INFO_CLT_ES_REQ,
		EN_QUERY_TRANS_INFO_ES_CLT_RSP,
		EN_QUERY_CRYPT_KEY_GET_TRANS_ES_XCS_REQ,
		EN_QUERY_CRYPT_KEY_GET_TRANS_XCS_ES_RSP,
		EN_QUERY_TRANS_INFO_ES_XCS_REQ,
		EN_QUERY_TRANS_INFO_XCS_ES_RSP,

		/* misc */
		EN_INIT_VBH_USER_SDK_MSG,
		EN_BLOCKCHAIN_STATISTICS_MSG,



		EN_MIN_VBH_MSG = 0X00000320
	};
}

#endif
