#ifndef VBH_COMMON_MACRO_DEF_H_076E0F629CAF11E9BDAA60F18A3A20D1
#define VBH_COMMON_MACRO_DEF_H_076E0F629CAF11E9BDAA60F18A3A20D1

#define DEF_STORAGE_DIR_NAME "storage"

#define DEF_UNIQUE_CMS_SERVICE_ID 1 //全局唯一CMS service id
#define DEF_ORDER_CPS_CONFIG_FILE_NAME "cps.cfg"
#define DEF_ORDER_CPS_LOG_FILE_NAME "cps.log"

#define DEF_BLOCK_CACHE_DIR_NAME "block_cache"
#define DEF_BLOCK_CACHE_FILE_SUBFIX ".cache"
#define DEF_BLOCK_CACHE_CIRCULAR_CONTROLLER_FILE_NAME "ca.ctl"

#define DEF_ANCHOR_CONFIG_FILE_NAME "anchor.cfg"
#define DEF_ANCHOR_LOG_FILE_NAME "anchor.log"

#define DEF_USER_HISTORY_DB_PATH_NAME "U_HIST_DB"
#define DEF_INFORMATION_HISTORY_DB_PATH_NAME "I_HIST_DB"
#define DEF_HISTORY_DB_HEAD_FILE_NAME ".hist_db_head"
#define DEF_HISTORY_DB_FILE_SUBFIX ".hdb"
#define DEF_WRITE_CACHE_HISTORY_DB_FILE_NAME "write_cache.hdb"


#define DEF_TRANSACTION_INDEX_PATH_NAME "T_IDX"
#define DEF_BLOCKCHAIN_STORAGE_PATH_NAME "BLOCK_CHAIN"
#define DEF_BLOCKCHAIN_HEAD_FILE_NAME ".bc_head"
#define DEF_BLOCKCHAIN_FILE_SUBFIX ".bc"

// 配置项名称
#define DEF_BLOCKCHAIN_STORAGE_BLOCK_PATH_NAME	"block"
// 区块存储位置
#define DEF_CFG_BLOCK_DATA_PATH												"VBH_BLOCK_DATA_PATH"
// 区块索引缓存大小，单位MB
#define DEF_CFG_BLOCK_INDEX_CACHE_SIZE_MB						"VBH_BLOCK_INDEX_CACHE_SIZE_MB"
// 区块数据缓存大小，单位MB
#define DEF_CFG_BLOCK_DATA_CACHE_SIZE_MB						"VBH_BLOCK_DATA_CACHE_SIZE_MB"

#endif // VBH_COMMON_MACRO_DEF_H_076E0F629CAF11E9BDAA60F18A3A20D1
