SHELL = /bin/sh

.PHONY: all
all:
	cd $(WORK_ROOT)/src/demo/demo_client/plugin && $(MAKE)
	cd $(WORK_ROOT)/src/demo/demo_client/demo_client && $(MAKE)
	
clean:
	cd $(WORK_ROOT)/src/demo/demo_client/plugin && $(MAKE) clean
	cd $(WORK_ROOT)/src/demo/demo_client/demo_client && $(MAKE) clean
