#ifndef S28_COMM_DEF_H_43879234792437934265234674238902347934267234782346782346824365
#define S28_COMM_DEF_H_43879234792437934265234674238902347934267234782346782346824365

#include "dsc/dsc_comm_def.h"

namespace S28_COMM_DEF
{
	enum
	{
		EN_S28_SCHEDULER_NODE_ID = 1,//这数值轻易不改
		EN_S28_SCHEDULER_NODE_TYPE = 999,//这数值轻易不改
		EN_S28_SCHEDULER_SERVICE_ID = 1,//这数值轻易不改
		EN_S28_SCHEDULER_SERVICE_TYPE = DSC::EN_MIN_USER_TASK_TYPE + 1,
		EN_S28_CLIENT_SDK_AGENT_SERVICE_TYPE,
		EN_S28_CLIENT_SDK_CALL_BACK_SERVICE_TYPE,
		//-------------------------------------------------------------------------------------------
		EN_S28_SUBSCRIBER_PUBLISHER_SERVICE_CONTAINER_TYPE,
		EN_S28_TCP_SCHEDULER_AGENT_TYPE,
		EN_S28_TCP_PUBLISHER_SERVICE_TYPE,
		EN_S28_TCP_SUBSCRIBER_SERVICE_TYPE
	};

	enum
	{
		EN_SUBSCRIBE_MESSAGE_MSG,
		EN_UNSUBSCRIBE_MESSAGE_MSG,
		EN_SUBSCRIBED_MESSAGE_CHANGE_NOTIFY_MSG,
		EN_UNSUBSCRIBED_MESSAGE_CHANGE_NOTIFY_MSG,
		//--------------------------------------------------------------------------------------------------------
		EN_REGIST_S28_TCP_PUBLISHER_SERVICE_REQ_MSG = DSC::EN_MIN_USER_MSG + 1,
		EN_REGIST_S28_TCP_PUBLISHER_SERVICE_RSP_MSG,
		EN_REGIST_S28_TCP_SUBSCRIBER_SERVICE_REQ_MSG,
		EN_REGIST_S28_TCP_SUBSCRIBER_SERVICE_RSP_MSG,
		EN_REGIST_PUBLISHE_TOPIC_REQ_MSG,
		EN_REGIST_PUBLISHE_TOPIC_RSP_MSG,
		EN_REGIST_SUBSCRIBER_TOPIC_REQ_MSG,
		EN_REGIST_SUBSCRIBER_TOPIC_RSP_MSG,
		EN_INNER_REGIST_PUBLISHE_TOPIC_REQ_MSG,
		EN_INNER_REGIST_PUBLISHE_TOPIC_RSP_MSG,
		EN_INNER_UNREGIST_PUBLISHE_TOPIC_REQ_MSG,
		EN_INNER_REGIST_SUBSCRIBER_TOPIC_REQ_MSG,
		EN_INNER_REGIST_SUBSCRIBER_TOPIC_RSP_MSG,
		EN_INNER_UNREGIST_SUBSCRIBER_TOPIC_REQ_MSG,
		EN_PUBLISHE_MESSAGE_MSG,
		EN_CLIENT_SUBSCRIBE_MESSAGE_MSG,
		EN_CLIENT_PUBLISHE_MESSAGE_MSG,
		EN_CLIENT_REGIST_USER_REQ_MSG,
		EN_REGIST_USER_REQ_MSG,
		EN_UNREGIST_USER_NOTIFY_MSG,
		EN_INNER_REGIST_USER_REQ_MSG,
		EN_INNER_REGIST_USER_RSP_MSG,
		EN_REGIST_USER_RSP_MSG,
		EN_REGIST_USER_2_FORWARDER_REQ_MSG,
		EN_CLIENT_SYNC_USER_INFO_REQ_MSG,
		EN_SYNC_USER_INFO_REQ_MSG,
		EN_SYNC_USER_INFO_RSP_MSG,
		EN_INNER_SYNC_USER_INFO_REQ_MSG,
		EN_ADD_USER_INFO_NOTIFY_MSG,
		EN_INNER_ADD_USER_INFO_NOTIFY_MSG,
		EN_DEL_USER_INFO_NOTIFY_MSG,
		EN_INNER_DEL_USER_INFO_NOTIFY_MSG,
		EN_CLIENT_PUBLISHE_MESSAGE_2_USER_MSG,
		EN_PUBLISHE_MESSAGE_2_GROUP_MSG,
		EN_PUBLISHE_MESSAGE_2_USER_MSG,
		EN_PUBLISHE_MESSAGE_2_MULTI_USER_MSG,
		EN_NETWORK_DISCONNECT_NOTIFY_MSG
	};
}

#endif
